[project]
name = "raccoon-ridelog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rene Calderon" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
raccoon-ridelog = "raccoon_ridelog:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
