[project]
name = "raccoon-ridelog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rene Calderon" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi", # WEB
    "uvicorn", # WEB Server
    "pydantic", # Valid DTOs
    "pydantic-settings", # Configuration based on .env
    "sqlalchemy", # ORM
    "asyncpg", # Postgres driver
    "pyjwt", # JWT
    "passlib[bcrypt]", # Hash and encoder
    "bcrypt", # Algoritm to encode
    "httpx", # HTTP Client
    "apscheduler", # Cron 
    "pandas", # Dataset
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-asyncio",
    "httpx",
]

[project.scripts]
raccoon-ridelog = "raccoon_ridelog:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
